services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: rmutlsport
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql  
    restart: unless-stopped


  app:
    build: .
    container_name: node-app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: 123456
      DB_NAME: rmutlsport
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: ["pm2-runtime", "start", "server.js"]  
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8000:80"
    depends_on:
      - db 
    restart: unless-stopped
 

volumes:
  db_data:
